slide_index:
    path:     /
    defaults: { _controller: "AdminBundle:TzeSlide:index" }
    methods:  GET

slide_new:
    path:     /new
    defaults: { _controller: "AdminBundle:TzeSlide:new" }
    methods:  [GET, POST]

slide_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:TzeSlide:edit" }
    methods:  [GET, POST]

slide_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:TzeSlide:update" }
    methods:  [POST, PUT]

slide_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:TzeSlide:delete" }
    methods:  [GET, DELETE]

slide_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:TzeSlide:deleteGroup" }
    methods:  POST