services:
    dit.manager.user:
        class: App\Tzevent\Service\UserBundle\Manager\UserManager
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true

    dit.manager.user.upload:
        class: App\Tzevent\Service\UserBundle\Manager\UploadManager
        arguments: ['@doctrine.orm.entity_manager','%kernel.root_dir%']
        public: true

    dit.handler.login_success_handler:
        class:  App\Tzevent\Service\UserBundle\Redirection\AfterLoginRedirection
        arguments:  ['@router', '@security.authorization_checker', '@service_container']