email_newsletter_index:
    path:     /
    defaults: { _controller: "AdminBundle:TzeEmailNewsletter:index" }
    methods:  GET

email_newsletter_new:
    path:     /new
    defaults: { _controller: "AdminBundle:TzeEmailNewsletter:new" }
    methods:  [GET, POST]

email_newsletter_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:TzeEmailNewsletter:edit" }
    methods:  [GET, POST]

email_newsletter_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:TzeEmailNewsletter:update" }
    methods:  [POST, PUT]

email_newsletter_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:TzeEmailNewsletter:delete" }
    methods:  [ GET, DELETE ]

email_newsletter_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:TzeEmailNewsletter:deleteGroup" }
    methods:  POST