participants_index:
  path:     /
  defaults: { _controller: "AdminBundle:TzeParticipants:index" }
  methods:  GET

participants_new:
  path:     /new
  defaults: { _controller: "AdminBundle:TzeParticipants:new" }
  methods:  [GET, POST]

participants_edit:
  path:     /{id}/edit
  defaults: { _controller: "AdminBundle:TzeParticipants:edit" }
  methods:  [GET, POST]

participants_update:
  path:     /{id}/update
  defaults: { _controller: "AdminBundle:TzeParticipants:update" }
  methods:  [POST, PUT]

participants_delete:
  path:     /{id}/delete
  defaults: { _controller: "AdminBundle:TzeParticipants:delete" }
  methods:  [GET, DELETE]

participants_delete_group:
  path:     /delete-group
  defaults: { _controller: "AdminBundle:TzeParticipants:deleteGroup" }
  methods:  POST