api_participants:
  path:     /participants
  defaults: { _controller: "ApiBundle:Api:participants" }
  methods:  GET

api_participants_new:
  path:     /participants/new
  defaults: { _controller: "ApiBundle:Api:newParticipants" }
  methods:  POST

#tze_login:
#  path: /login
#  defaults: { _controller: UserBundle:Security:login }
#
api_partenaires:
  path:     /partenaires
  defaults: { _controller: "ApiBundle:Api:partenairesList" }
  methods:  GET

api_organisateur:
  path:     /organisateurs
  defaults: { _controller: "ApiBundle:Api:organisateur" }
  methods:  GET
