front_site:
    resource: "@FrontSiteBundle/Resources/config/routing.yml"
    prefix:   /

app_file:
    resource: '@AdminBundle/Resources/config/routing/slide.yml'
    prefix:   /admin

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

api_routage:
    resource:  "@ApiBundle/Ressources/config/routing.yml"
    prefix:   /api

tze_api:
    resource: "@FrontSiteBundle/Resources/config/routing/api.yml"
    prefix:   /teste-api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

