home_site_index:
    path:     /
    defaults: { _controller: "FrontSiteBundle:TzeHome:index" }
    methods:  GET

email_news_new:
    path:     /new
    defaults: { _controller: "FrontSiteBundle:TzeFooter:show" }
    methods:  [GET, POST]

show_participants:
    path:     /participant
    defaults: { _controller: "FrontSiteBundle:TzeHome:showparticipant" }
    methods:  GET
